app/mod_tbls1/views.py
# Import flask dependencies
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for

from functools import wraps

from app import login_required
from app.mod_tbls1 import controllers
from app.mod_auth import controllers as ctrl_auth

from config import REGISTERS_PER_PAGE
import utils

def _get_unauthorized_view():
    return redirect(url_for('no_autorizado'))

def roles_required(*roles):
    """Decorador que especifica que un usuario debe tener todos los 
    roles especificados."""
    def wrapper(fn):
        @wraps(fn)
        def decorated_view(*args, **kwargs):
            id_usuario = session['id_usuario']
            continuar = ctrl_auth.roles_required(id_usuario, roles)
            if(continuar):
                return fn(*args, **kwargs)
            return _get_unauthorized_view()
        return decorated_view
    return wrapper

def roles_accepted(*roles):
    """Decorador que especifica que un usuario debe tener al menos uno
    de los roles especificados"""
    def wrapper(fn):
        @wraps(fn)
        def decorated_view(*args, **kwargs):
            id_usuario = session['id_usuario']
            continuar = ctrl_auth.roles_accepted(id_usuario, roles)
            if(continuar):
                return fn(*args, **kwargs)
            return _get_unauthorized_view()
        return decorated_view
    return wrapper

# Define the blueprint
mod_tbls1 = Blueprint('tbls1', __name__, url_prefix='/tbls1')

# Set the route and accepted methods
@mod_tbls1.route('/administrar_departamentos', methods=['GET', 'POST'])
@mod_tbls1.route('/administrar_departamentos/pagina/<int:pagina>', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMLOC')
def administrar_departamentos(pagina=1):
    items = []
    error = None
    id_usuario = session['id_usuario']
    cadena = ""
    if request.method == 'GET':
        busqueda = session['busqueda']
        if busqueda == True:
            cadena = session["cadena"]
            campo = session["campos"]
            items = controllers.buscar_departamentos(cadena)
        else:
            items = controllers.listar_departamentos()
    elif request.method == 'POST':
        if request.form["action"] == "Buscar":
            cadena = request.form["cadena"]
            session['cadena'] = cadena
            items = controllers.buscar_departamentos(cadena)
            if len(items) == 0:
                session['busqueda'] = False
                flash("No se encontraron coincidencias")
            else:
                session['busqueda'] = True
        elif request.form["action"] == "Limpiar":
            session['busqueda'] = False
            pagina = 1
            items = controllers.listar_departamentos()
        elif request.form["action"] == "Salir":
            session['busqueda'] = False
            return redirect(url_for('auth.menu_principal'))
        elif request.form["action"] == "Crear":
            return redirect(url_for('tbls1.crear_departamentos'))
        elif request.form["action"] == "Modificar":
            seleccionados = request.form.getlist("seleccionados")
            error = controllers.validaciones_modificar_departamento(seleccionados)
            if error == None: #Si paso las validaciones
                return redirect(url_for('tbls1.modificar_departamentos', depmodif=seleccionados[0]))
            else: #No paso las validaciones
                return render_template('tbls1/administrar_departamentos.html', \
                items=items, id_usuario=id_usuario, error=error, \
                cadena=cadena)
        elif request.form["action"] == "Eliminar":
            seleccionados = request.form.getlist("seleccionados")
            error = controllers.validaciones_eliminar_departamento(seleccionados)
            if error == None: #Si paso las validaciones
                resultado = controllers.eliminar_departamento(seleccionados)
                if resultado == 'OK':
                    flash(u"La operaci\xf3n se realiz\xf3 con \xe9xito")
                    items = controllers.listar_departamentos()
                else:
                    error = resultado
                    items = controllers.listar_departamentos()

    paginacion_siguiente = utils.paginacion_siguiente(items, \
    pagina, REGISTERS_PER_PAGE)
    paginacion_anterior = utils.paginacion_anterior(items, pagina)
    paginacion_primero = utils.paginacion_primero(items, pagina)
    paginacion_ultimo = utils.paginacion_ultimo(items, pagina, \
    REGISTERS_PER_PAGE)

    items = utils.paginacion(items, pagina, REGISTERS_PER_PAGE)

    return render_template('tbls1/administrar_departamentos.html', items=items, \
    id_usuario=id_usuario, cadena=cadena, error=error, \
    pg_ante=paginacion_anterior, pg_sgte=paginacion_siguiente, \
    pg_prim=paginacion_primero, pg_ultm=paginacion_ultimo)

@mod_tbls1.route('/alta_departamentos', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMLOC')
def crear_departamentos():
    id_usuario = session['id_usuario']
    error = None
    if request.method == 'POST':
        if request.form["action"] == "Salir":
            return redirect(url_for('tbls1.administrar_departamentos'))

        p_nombre = request.form['nombre']

        if not controllers.verificar_datos_requeridos_alta_dpto(p_nombre):
            error = "Datos requeridos no ingresados"
            return render_template('tbls1/crear_departamentos.html', \
            id_usuario=id_usuario, error=error, nombre=p_nombre)

        resultado = controllers.insertar_departamento(p_nombre)

        if resultado == 'OK':
            flash(u"La operaci\xf3n se realiz\xf3 con \xe9xito")
            if request.form["action"] == "Guardar y Continuar":
                return render_template('tbls1/crear_departamentos.html', \
                id_usuario=id_usuario, error=error)
            else: #Eligio Guardar
                return redirect(url_for('tbls1.administrar_departamentos'))
        else:
            error = resultado
            return render_template('tbls1/crear_departamentos.html', \
            id_usuario=id_usuario, error=error, nombre=p_nombre)

    return render_template('tbls1/crear_departamentos.html', id_usuario = \
    id_usuario, error=error, nombre="")

@mod_tbls1.route('/modificacion_departamentos/<depmodif>', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMLOC')
def modificar_departamentos(depmodif):
    id_usuario = session['id_usuario']
    error = None
    if request.method == 'POST':
        if request.form["action"] == "Salir":
            return redirect(url_for('tbls1.administrar_departamentos'))

        p_nombre = request.form['nombre']

        if not controllers.verificar_datos_requeridos_modif_dpto(\
        p_nombre):
            error = "Datos requeridos no ingresados"
            return render_template('tbls1/modificar_departamentos.html', \
            id_usuario=id_usuario, error=error, nombre=p_nombre)

        resultado = controllers.modificar_departamento(depmodif, p_nombre)

        if resultado == 'OK':
            flash(u"La operaci\xf3n se realiz\xf3 con \xe9xito")
            return redirect(url_for('tbls1.administrar_departamentos'))
        else:
            error = resultado
            return render_template('tbls1/modificar_departamentos.html', \
            id_usuario=id_usuario, error=error, nombre=p_nombre)

    dep = controllers.obtener_departamento(depmodif)

    if dep == None:
        error = "El departamento no existe"
        return render_template('tbls1/modificar_departamentos.html', \
        id_usuario=id_usuario, error=error, nombre="")

    return render_template('tbls1/modificar_departamentos.html', \
    id_usuario = id_usuario, error=error, nombre=dep.get('nombre'))

@mod_tbls1.route('/administrar_distritos/<departamento>', methods=['GET', 'POST'])
@mod_tbls1.route('/administrar_distritos/<departamento>/pagina/<int:pagina>', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMLOC')
def administrar_distritos(departamento, pagina=1):
    items = []
    error = None
    id_usuario = session['id_usuario']
    cadena = ""
    campo = "todos"
    if request.method == 'GET':
        busqueda = session['busqueda']
        if busqueda == True:
            cadena = session["cadena"]
            campo = session["campos"]
            items = controllers.buscar_distritos(cadena, departamento)
        else:
            items = controllers.listar_distritos(departamento)
    elif request.method == 'POST':
        if request.form["action"] == "Buscar":
            cadena = request.form["cadena"]
            session['cadena'] = cadena
            items = controllers.buscar_distritos(cadena, departamento)
            if len(items) == 0:
                session['busqueda'] = False
                flash("No se encontraron coincidencias")
            else:
                session['busqueda'] = True
        elif request.form["action"] == "Limpiar":
            session['busqueda'] = False
            pagina = 1
            items = controllers.listar_distritos(departamento)
        elif request.form["action"] == "Salir":
            session['busqueda'] = False
            return redirect(url_for('tbls1.administrar_departamentos'))
        elif request.form["action"] == "Crear":
            return redirect(url_for('tbls1.crear_distritos', \
            departamento=departamento))
        elif request.form["action"] == "Modificar":
            seleccionados = request.form.getlist("seleccionados")
            error = controllers.validaciones_modificar_distrito(seleccionados)
            if error == None: #Si paso las validaciones
                return redirect(url_for('tbls1.modificar_distritos', distmodif=seleccionados[0]))
            else: #No paso las validaciones
                return render_template('tbls1/administrar_distritos.html', \

app/templates/tbls1/administrar_barrios.html
{% extends "base.html" %}
{% block title %}Administrar Barrios{% endblock %}
{% block body %}
  <h2>Administrar Barrios</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><select name="campos">
                  <option {% if set_etc == "todos" %} selected="selected" {% endif %} value="todos">Todos</option>
                  <option {% if set_etc == "codigo" %} selected="selected" {% endif %} value="codigo">C&oacute;digo</option>
                  <option {% if set_etc == "nombre" %} selected="selected" {% endif %} value="nombre">Nombre</option>
              </select></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><input type=submit name="action" value=Crear></TD>
              <TD><input type=submit name="action" value=Modificar></TD>
              <TD><input type=submit name="action" value=Eliminar onclick="return confirm('¿Est&aacute; seguro?');"></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>C&oacute;digo</th>
              <th>Nombre</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.codigo}}</TD>
            <TD class="c2">{{item.nombre}}</TD>
          </TR>
          {% endfor %}
      </table>
      <table>
          <tr>
              {% if pg_prim > 0 %}<td><a href="{{ url_for('tbls1.administrar_barrios', distrito=dist, pagina=pg_prim) }}">Primera</a></td>{% endif %}
              {% if pg_ante > 0 %}<td><a href="{{ url_for('tbls1.administrar_barrios', distrito=dist, pagina=pg_ante) }}">Anterior</a></td>{% endif %}
              {% if pg_sgte > 0 %}<td><a href="{{ url_for('tbls1.administrar_barrios', distrito=dist, pagina=pg_sgte) }}">Siguiente</a></td>{% endif %}
              {% if pg_ultm > 0 %}<td><a href="{{ url_for('tbls1.administrar_barrios', distrito=dist, pagina=pg_ultm) }}">Ultima</a></td>{% endif %}
          </tr>
      </table>
    </form>
{% endblock %}

app/templates/tbls1/administrar_departamentos.html
{% extends "base.html" %}
{% block title %}Administrar Departamentos{% endblock %}
{% block body %}
  <h2>Administrar Departamentos</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><input type=submit name="action" value=Crear></TD>
              <TD><input type=submit name="action" value=Modificar></TD>
              <TD><input type=submit name="action" value=Eliminar onclick="return confirm('¿Est&aacute; seguro?');"></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>Nombre</th>
              <th>Administrar Distritos</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.nombre}}</TD>
            <TD><a href="{{ url_for('tbls1.administrar_distritos', departamento=item.id) }}">Administrar Distritos</a></TD>
          </TR>
          {% endfor %}
      </table>
      <table>
          <tr>
              {% if pg_prim > 0 %}<td><a href="{{ url_for('tbls1.administrar_departamentos', pagina=pg_prim) }}">Primera</a></td>{% endif %}
              {% if pg_ante > 0 %}<td><a href="{{ url_for('tbls1.administrar_departamentos', pagina=pg_ante) }}">Anterior</a></td>{% endif %}
              {% if pg_sgte > 0 %}<td><a href="{{ url_for('tbls1.administrar_departamentos', pagina=pg_sgte) }}">Siguiente</a></td>{% endif %}
              {% if pg_ultm > 0 %}<td><a href="{{ url_for('tbls1.administrar_departamentos', pagina=pg_ultm) }}">Ultima</a></td>{% endif %}
          </tr>
      </table>
    </form>
{% endblock %}

app/templates/tbls1/administrar_distritos.html
{% extends "base.html" %}
{% block title %}Administrar Distritos{% endblock %}
{% block body %}
  <h2>Administrar Distritos</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><input type=submit name="action" value=Crear></TD>
              <TD><input type=submit name="action" value=Modificar></TD>
              <TD><input type=submit name="action" value=Eliminar onclick="return confirm('¿Est&aacute; seguro?');"></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>Nombre</th>
              <th>Administrar Barrios</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.nombre}}</TD>
            <TD><a href="{{ url_for('tbls1.administrar_barrios', distrito=item.id) }}">Administrar Barrios</a></TD>
          </TR>
          {% endfor %}
      </table>
      <table>
          <tr>
              {% if pg_prim > 0 %}<td><a href="{{ url_for('tbls1.administrar_distritos', departamento=dpto, pagina=pg_prim) }}">Primera</a></td>{% endif %}
              {% if pg_ante > 0 %}<td><a href="{{ url_for('tbls1.administrar_distritos', departamento=dpto, pagina=pg_ante) }}">Anterior</a></td>{% endif %}
              {% if pg_sgte > 0 %}<td><a href="{{ url_for('tbls1.administrar_distritos', departamento=dpto, pagina=pg_sgte) }}">Siguiente</a></td>{% endif %}
              {% if pg_ultm > 0 %}<td><a href="{{ url_for('tbls1.administrar_distritos', departamento=dpto, pagina=pg_ultm) }}">Ultima</a></td>{% endif %}
          </tr>
      </table>
    </form>
{% endblock %}

app/templates/tbls1/administrar_registros1.html
{% extends "base.html" %}
{% block title %}Administrar Registros{% endblock %}
{% block body %}
  <h2>Administrar Registros</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><select name="campos">
                  <option {% if set_etc == "todos" %} selected="selected" {% endif %} value="todos">Todos</option>
                  <option {% if set_etc == "manzana" %} selected="selected" {% endif %} value="manzana">Manzana</option>
                  <option {% if set_etc == "direccion" %} selected="selected" {% endif %} value="direccion">Direcci&oacute;n</option>
                  <option {% if set_etc == "latitud" %} selected="selected" {% endif %} value="latitud">Latitud</option>
                  <option {% if set_etc == "longitud" %} selected="selected" {% endif %} value="longitud">Longitud</option>
              </select></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><button type=submit name="action" value=Detalles>Ver Detalles</button></TD>
              <TD><input type=submit name="action" value=Eliminar onclick="return confirm('¿Est&aacute; seguro?');"></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>Manzana</th>
              <th>Direcci&oacute;n</th>
              <th>Latitud</th>
              <th>Longitud</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.manzana}}</TD>
            <TD class="c2">{{item.direccion}}</TD>
            <TD class="c3">{{item.latitud}}</TD>
            <TD class="c4">{{item.longitud}}</TD>
          </TR>
          {% endfor %}
      </table>
    </form>
{% endblock %}

app/templates/tbls1/administrar_tbls1.html
{% extends "base.html" %}
{% block title %}Administrar Planillas{% endblock %}
{% block body %}
  <h2>Administrar Planillas</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><select name="campos">
                  <option {% if set_etc == "todos" %} selected="selected" {% endif %} value="todos">Todos</option>
                  <option {% if set_etc == "departamento" %} selected="selected" {% endif %} value="departamento">Departamento</option>
                  <option {% if set_etc == "distrito" %} selected="selected" {% endif %} value="distrito">Distrito</option>
                  <option {% if set_etc == "barrio" %} selected="selected" {% endif %} value="barrio">Barrio</option>
                  <option {% if set_etc == "usuario" %} selected="selected" {% endif %} value="usuario">Usuario</option>
                  <option {% if set_etc == "fecha" %} selected="selected" {% endif %} value="fecha">Fecha</option>
              </select></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><button type=submit name="action" value=Detalles>Ver Detalles</button></TD>
              <TD><input type=submit name="action" value=Eliminar onclick="return confirm('¿Est&aacute; seguro?');"></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>Departamento</th>
              <th>Distrito</th>
              <th>Barrio</th>
              <th>Usuario</th>
              <th>Fecha</th>
              <th>Administrar Registros</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.departamento}}</TD>
            <TD class="c2">{{item.distrito}}</TD>
            <TD class="c3">{{item.barrio}}</TD>
            <TD class="c4">{{item.usuario}}</TD>
            <TD class="c5">{{item.fecha}}</TD>
            <TD><a href="{{ url_for('tbls1.administrar_registros', planilla=item.id) }}">Administrar Registros</a></TD>
          </TR>
          {% endfor %}
      </table>
      <table>
          <tr>
              {% if pg_prim > 0 %}<td><a href="{{ url_for('tbls1.administrar_planillas', pagina=pg_prim) }}">Primera</a></td>{% endif %}
              {% if pg_ante > 0 %}<td><a href="{{ url_for('tbls1.administrar_planillas', pagina=pg_ante) }}">Anterior</a></td>{% endif %}
              {% if pg_sgte > 0 %}<td><a href="{{ url_for('tbls1.administrar_planillas', pagina=pg_sgte) }}">Siguiente</a></td>{% endif %}
              {% if pg_ultm > 0 %}<td><a href="{{ url_for('tbls1.administrar_planillas', pagina=pg_ultm) }}">Ultima</a></td>{% endif %}
          </tr>
      </table>
    </form>
{% endblock %}

app/templates/tbls1/administrar_tipo_predio.html
{% extends "base.html" %}
{% block title %}Administrar Tipo Predio{% endblock %}
{% block body %}
  <h2>Administrar Tipo Predio</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><input type=submit name="action" value=Crear></TD>
              <TD><input type=submit name="action" value=Modificar></TD>
              <TD><input type=submit name="action" value=Eliminar onclick="return confirm('¿Est&aacute; seguro?');"></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>Nombre</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.nombre}}</TD>
          </TR>
          {% endfor %}
      </table>
    </form>
{% endblock %}

app/templates/tbls1/crear_barrios.html
{% extends "base.html" %}
{% block title %}Crear Barrios{% endblock %}
{% block body %}
    <h2>Crear Barrios</h2>
    {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
    <form name="formulario" action="" method=post>
        <table>
            <tr>
                <td>C&oacute;digo:</td>
                <td><input type=text name=codigo size=20 maxlength=8 value="{{ codigo }}"></td>
            </tr>
            <tr>
                <td>(*) Nombre:</td>
                <td><input type=text name=nombre size=20 maxlength=35 value="{{ nombre }}"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>(*) Datos requeridos</td>
            </tr>
        </table>
        <table>
            <tr>
                <td><input type=submit name="action" value="Guardar"></td>
                <td><input type=submit name="action" value="Guardar y Continuar"></td>
                <td><button type=submit name="action" value="Salir" onclick="return confirm('Los datos no ser&aacute;n almacenados');">Cancelar</button></td>
            </tr>
        </table>
    </form>
{% endblock %}

app/templates/tbls1/crear_departamentos.html
{% extends "base.html" %}
{% block title %}Crear Departamentos{% endblock %}
{% block body %}
    <h2>Crear Departamentos</h2>
    {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
    <form name="formulario" action="" method=post>
        <table>
            <tr>
                <td>(*) Nombre:</td>
                <td><input type=text name=nombre size=20 maxlength=35 value="{{ nombre }}"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>(*) Datos requeridos</td>
            </tr>
        </table>
        <table>
            <tr>
                <td><input type=submit name="action" value="Guardar"></td>
                <td><input type=submit name="action" value="Guardar y Continuar"></td>
                <td><button type=submit name="action" value="Salir" onclick="return confirm('Los datos no ser&aacute;n almacenados');">Cancelar</button></td>
            </tr>
        </table>
    </form>
{% endblock %}

app/templates/tbls1/crear_tipo_control.html
{% extends "base.html" %}
{% block title %}Crear Tipo Control{% endblock %}
{% block body %}
    <h2>Crear Tipo Control</h2>
    {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
    <form name="formulario" action="" method=post>
        <table>
            <tr>
                <td>(*) Nombre:</td>
                <td><input type=text name=nombre size=20 maxlength=20 value="{{ nombre }}"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>(*) Datos requeridos</td>
            </tr>
        </table>
        <table>
            <tr>
                <td><input type=submit name="action" value="Guardar"></td>
                <td><input type=submit name="action" value="Guardar y Continuar"></td>
                <td><button type=submit name="action" value="Salir" onclick="return confirm('Los datos no ser&aacute;n almacenados');">Cancelar</button></td>
            </tr>
        </table>
    </form>
{% endblock %}

app/templates/tbls1/detalles_tbls1.html
{% extends "base.html" %}
{% block title %}Detalles Planillas{% endblock %}
{% block body %}
    <h2>Detalles Planillas</h2>
    {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
    <form action="" method=post>
        <table>
            <tr>
                <td>Departamento:</td>
                <td><input type=text name=nombre size=20 value="{{ departamento }}" disabled></td>
            </tr>
            <tr>
                <td>Distrito:</td>
                <td><input type=text name=nombre size=20 value="{{ distrito }}" disabled></td>
            </tr>
            <tr>
                <td>Barrio:</td>
                <td><input type=text name=nombre size=20 value="{{ barrio }}" disabled></td>
            </tr>
            <tr>
                <td>Usuario:</td>
                <td><input type=text name=nombre size=20 value="{{ usuario }}" disabled></td>
            </tr>
            <tr>
                <td>Fecha:</td>
                <td><input type=text name=nombre size=20 value="{{ fecha }}" disabled></td>
            </tr>
        </table>
        <table>
            <tr>
                <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
            </tr>
        </table>
</form>
{% endblock %}

app/templates/tbls1/modificar_barrios.html
{% extends "base.html" %}
{% block title %}Modificar Barrios{% endblock %}
{% block body %}
    <h2>Modificar Barrios</h2>
    {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
    <form action="" method=post>
        <table>
            <tr>
                <td>C&oacute;digo:</td>
                <td><input type=text name=codigo size=20 maxlength=8 value="{{ codigo }}"></td>
            </tr>
            <tr>
                <td>(*) Nombre:</td>
                <td><input type=text name=nombre size=20 maxlength=35 value="{{ nombre }}"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>(*) Datos requeridos</td>
            </tr>
        </table>
        <table>
            <tr>
                <td><input type=submit name="action" value="Guardar"></td>
                <td><button type=submit name="action" value="Salir" onclick="return confirm('Los datos no ser&aacute;n almacenados');">Cancelar</button></td>
            </tr>
        </table>
</form>
{% endblock %}