app/mod_roles/views.py
# Import flask dependencies
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for

from functools import wraps

from app import login_required
from app.mod_roles import controllers
from app.mod_auth import controllers as ctrl_auth

from config import REGISTERS_PER_PAGE
import utils

def _get_unauthorized_view():
    return redirect(url_for('no_autorizado'))

def roles_required(*roles):
    """Decorador que especifica que un usuario debe tener todos los 
    roles especificados."""
    def wrapper(fn):
        @wraps(fn)
        def decorated_view(*args, **kwargs):
            id_usuario = session['id_usuario']
            continuar = ctrl_auth.roles_required(id_usuario, roles)
            if(continuar):
                return fn(*args, **kwargs)
            return _get_unauthorized_view()
        return decorated_view
    return wrapper

def roles_accepted(*roles):
    """Decorador que especifica que un usuario debe tener al menos uno
    de los roles especificados"""
    def wrapper(fn):
        @wraps(fn)
        def decorated_view(*args, **kwargs):
            id_usuario = session['id_usuario']
            continuar = ctrl_auth.roles_accepted(id_usuario, roles)
            if(continuar):
                return fn(*args, **kwargs)
            return _get_unauthorized_view()
        return decorated_view
    return wrapper

# Define the blueprint
mod_roles = Blueprint('roles', __name__, url_prefix='/roles')

@mod_roles.route('/', methods=['GET', 'POST'])
@mod_roles.route('/pagina/<int:pagina>', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMROL')
def administrar_roles(pagina=1):
    items = []
    error = None
    id_usuario = session['id_usuario']
    cadena = ""
    campo = "todos"
    if request.method == 'GET':
        busqueda = session['busqueda']
        if busqueda == True:
            cadena = session["cadena"]
            campo = session["campos"]
            items = controllers.buscar_roles(cadena, campo)
        else:
            items = controllers.listar_roles()
    elif request.method == 'POST':
        if request.form["action"] == "Buscar":
            cadena = request.form["cadena"]
            campo = request.form["campos"]
            session['cadena'] = cadena
            session['campos'] = campo
            items = controllers.buscar_roles(cadena, campo)
            if len(items) == 0:
                session['busqueda'] = False
                flash("No se encontraron coincidencias")
            else:
                session['busqueda'] = True
        elif request.form["action"] == "Limpiar":
            session['busqueda'] = False
            pagina = 1
            items = controllers.buscar_roles()
        elif request.form["action"] == "Salir":
            session['busqueda'] = False
            return redirect(url_for('auth.menu_principal'))
        elif request.form["action"] == "Crear":
            return redirect(url_for('roles.crear_roles'))
        elif request.form["action"] == "Modificar":
            seleccionados = request.form.getlist("seleccionados")
            error = controllers.validaciones_modificar_rol(seleccionados)
            if error == None: #Si paso las validaciones
                return redirect(url_for('roles.modificar_roles', rolmodif=seleccionados[0]))
        elif request.form["action"] == "Eliminar":
            seleccionados = request.form.getlist("seleccionados")
            error = controllers.validaciones_eliminar_rol(seleccionados)
            if error == None: #Si paso las validaciones
                resultado = controllers.eliminar_rol(seleccionados)
                if resultado == 'OK':
                    flash(u"La operaci\xf3n se realiz\xf3 con \xe9xito")
                    items = controllers.listar_roles()
                else:
                    error = resultado

    paginacion_siguiente = utils.paginacion_siguiente(items, \
    pagina, REGISTERS_PER_PAGE)
    paginacion_anterior = utils.paginacion_anterior(items, pagina)
    items = utils.paginacion(items, pagina, REGISTERS_PER_PAGE)

    return render_template('roles/administrar_roles.html', items=items, \
    id_usuario=id_usuario, error=error, cadena=cadena, set_etc=campo,\
    pg_sgte=paginacion_siguiente, pg_ante=paginacion_anterior)

@mod_roles.route('/alta', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMROL')
def crear_roles():
    id_usuario = session['id_usuario']
    error = None
    if request.method == 'POST':
        if request.form["action"] == "Salir":
            return redirect(url_for('roles.administrar_roles'))

        p_nombre = request.form['nombre']
        p_descripcion = request.form['descripcion']

        if not controllers.verificar_datos_requeridos_alta(p_nombre, \
        p_descripcion):
            error = "Datos requeridos no ingresados"
            return render_template('roles/crear_roles.html', \
            id_usuario=id_usuario, error=error, nombre=p_nombre, \
            descripcion=p_descripcion)

        resultado = controllers.insertar_rol(p_nombre, \
        p_descripcion)

        if resultado == 'OK':
            flash(u"La operaci\xf3n se realiz\xf3 con \xe9xito")
            if request.form["action"] == "Guardar y Continuar":
                return render_template('roles/crear_roles.html', \
                id_usuario=id_usuario, error=error)
            else: #Eligio Guardar
                return redirect(url_for('roles.administrar_roles'))
        else:
            error = resultado
            return render_template('roles/crear_roles.html', \
            id_usuario=id_usuario, error=error, nombre=p_nombre, \
            descripcion=p_descripcion)

    return render_template('roles/crear_roles.html', id_usuario = \
    id_usuario, error=error, nombre="", descripcion="")

@mod_roles.route('/modificacion/<rolmodif>', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMROL')
def modificar_roles(rolmodif):
    id_usuario = session['id_usuario']
    error = None
    if request.method == 'POST':
        if request.form["action"] == "Salir":
            return redirect(url_for('roles.administrar_roles'))

        p_nombre = request.form['nombre']
        p_descripcion = request.form['descripcion']

        if not controllers.verificar_datos_requeridos_modificacion(\
        p_nombre, p_descripcion):
            error = "Datos requeridos no ingresados"
            return render_template('roles/modificar_roles.html', \
            id_usuario=id_usuario, error=error, nombre=p_nombre, \
            descripcion=p_descripcion)

        resultado = controllers.modificar_rol(rolmodif, \
        p_nombre, p_descripcion)

        if resultado == 'OK':
            flash(u"La operaci\xf3n se realiz\xf3 con \xe9xito")
            return redirect(url_for('roles.administrar_roles'))
        else:
            error = resultado
            return render_template('roles/modificar_roles.html', \
            id_usuario=id_usuario, error=error, nombre=p_nombre, \
            descripcion=p_descripcion)

    rol = controllers.obtener_rol(rolmodif)

    if rol == None:
        error = "El rol no existe"
        return render_template('roles/modificar_roles.html', \
        id_usuario=id_usuario, error=error, nombre="", descripcion="")

    return render_template('roles/modificar_roles.html', \
    id_usuario = id_usuario, error=error, nombre=rol.get('nombre'), \
    descripcion=rol.get('descripcion'))

@mod_roles.route('/permisos/<rol>', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMROL')
def administrar_permisos(rol):
    items = []
    error = None
    id_usuario = session['id_usuario']
    cadena = ""
    campo = "todos"
    if request.method == 'GET':
        busqueda = session['busqueda']
        if busqueda == True:
            cadena = session["cadena"]
            campo = session["campos"]
            items = controllers.buscar_permisos(cadena, campo)
        else:
            items = controllers.listar_permisos(rol)
    elif request.method == 'POST':
        if request.form["action"] == "Buscar":
            cadena = request.form["cadena"]
            campo = request.form["campos"]
            session['cadena'] = cadena
            session['campos'] = campo
            items = controllers.buscar_permisos(cadena, campo, rol)
            if len(items) == 0:
                session['busqueda'] = False
                flash("No se encontraron coincidencias")
            else:
                session['busqueda'] = True
        elif request.form["action"] == "Limpiar":
            session['busqueda'] = False
            items = controllers.listar_permisos(rol)
        elif request.form["action"] == "Salir":
            session['busqueda'] = False
            return redirect(url_for('roles.administrar_roles'))
        elif request.form["action"] == "Asignar":
            return redirect(url_for('roles.asignar_permisos_rol', rol=rol))
        elif request.form["action"] == "Quitar":
            seleccionados = request.form.getlist("seleccionados")
            error = controllers.validaciones_quitar_permisos_rol(seleccionados)
            if error == None: #Si paso las validaciones
                resultado = controllers.quitar_permisos_rol(seleccionados, \
                rol)
                if resultado == 'OK':
                    flash(u"La operaci\xf3n se realiz\xf3 con \xe9xito")
                    items = controllers.listar_permisos(rol)
                else:
                    error = resultado

    return render_template('roles/administrar_permisos.html', items=items, \
    id_usuario=id_usuario, error=error, cadena=cadena, set_etc=campo)

@mod_roles.route('/permisos/asignar/<rol>', methods=['GET', 'POST'])
@login_required
@roles_accepted('ADMROL')
def asignar_permisos_rol(rol):
    id_usuario = session['id_usuario']
    items = []
    error = None
    cadena = ""

app/templates/roles/administrar_permisos.html
{% extends "base.html" %}
{% block title %}Administrar Permisos{% endblock %}
{% block body %}
  <h2>Administrar Permisos</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><select name="campos">
                  <option {% if set_etc == "todos" %} selected="selected" {% endif %} value="todos">Todos</option>
                  <option {% if set_etc == "nombre" %} selected="selected" {% endif %} value="nombre">Nombre</option>
                  <option {% if set_etc == "descripcion" %} selected="selected" {% endif %} value="descripcion">Descripci&oacute;n</option>
              </select></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><button type=submit name="action" value=Asignar>Asignar</button></TD>
              <TD><input type=submit name="action" value=Quitar onclick="return confirm('¿Est&aacute; seguro?');"></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>Nombre</th>
              <th>Descripci&oacute;n</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.nombre}}</TD>
            <TD class="c2">{{item.descripcion}}</TD>
          </TR>
          {% endfor %}
      </table>
    </form>
{% endblock %}

app/templates/roles/administrar_roles.html
{% extends "base.html" %}
{% block title %}Administrar Roles{% endblock %}
{% block body %}
  <h2>Administrar Roles</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><select name="campos">
                  <option {% if set_etc == "todos" %} selected="selected" {% endif %} value="todos">Todos</option>
                  <option {% if set_etc == "nombre" %} selected="selected" {% endif %} value="nombre">Nombre</option>
                  <option {% if set_etc == "descripcion" %} selected="selected" {% endif %} value="descripcion">Descripci&oacute;n</option>
              </select></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><input type=submit name="action" value=Crear></TD>
              <TD><input type=submit name="action" value=Modificar></TD>
              <TD><input type=submit name="action" value=Eliminar onclick="return confirm('¿Est&aacute; seguro?');"></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>Nombre</th>
              <th>Descripci&oacute;n</th>
              <th>Permisos</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.nombre}}</TD>
            <TD class="c2">{{item.descripcion}}</TD>
            <TD><a href="{{ url_for('roles.administrar_permisos', rol=item.id) }}">Permisos</a></TD>
          </TR>
          {% endfor %}
      </table>
      <table>
          <tr>
              {% if pg_ante > 0 %}<td><a href="{{ url_for('usuarios.administrar_roles', pagina=pg_ante) }}">Anterior</a></td>{% endif %}
              {% if pg_sgte > 0 %}<td><a href="{{ url_for('usuarios.administrar_roles', pagina=pg_sgte) }}">Siguiente</a></td>{% endif %}
          </tr>
      </table>
    </form>
{% endblock %}

app/templates/roles/asignar_permisos_roles.html
{% extends "base.html" %}
{% block title %}Asignar Permisos de Rol{% endblock %}
{% block body %}
  <h2>Asignar Permisos de Rol</h2>
  {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
  <form action="" method=post>
      <table>
          <TR>
              <TD><input type=text name=cadena size=30 value="{{ cadena }}"></TD>
              <TD><select name="campos">
                  <option {% if set_etc == "todos" %} selected="selected" {% endif %} value="todos">Todos</option>
                  <option {% if set_etc == "nombre" %} selected="selected" {% endif %} value="nombre">Nombre</option>
                  <option {% if set_etc == "descripcion" %} selected="selected" {% endif %} value="descripcion">Descripci&oacute;n</option>
              </select></TD>
              <TD><input type=submit name="action" value=Buscar></TD>
              <TD><input type=submit name="action" value=Limpiar></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <TD><input type=submit name="action" value=Asignar></TD>
              <TD><button type=submit name="action" value=Salir>Regresar</button></TD>
          </TR>
      </table>
      <br>
      <table>
          <TR>
              <th>Seleccionar</th>
              <th>Nombre</th>
              <th>Descripci&oacute;n</th>
          </TR>
          {% for item in items %}
          <TR>
            <td><input type=checkbox name=seleccionados value="{{ item.id }}"></td>
            <TD class="c1">{{item.nombre}}</TD>
            <TD class="c2">{{item.descripcion}}</TD>
          </TR>
          {% endfor %}
      </table>
    </form>
{% endblock %}

app/templates/roles/crear_roles.html
{% extends "base.html" %}
{% block title %}Crear Roles{% endblock %}
{% block body %}
    <h2>Crear Roles</h2>
    {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
    <form name="formulario" action="" method=post>
        <table>
            <tr>
                <td>(*) Nombre:</td>
                <td><input type=text name=nombre size=15 maxlength=15 value="{{ nombre }}"></td>
            </tr>
            <tr>
                <td>(*) Descripci&oacute;n:</td>
                <td><input type=text name=descripcion size=30 maxlength=30 value="{{ descripcion }}"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>(*) Datos requeridos</td>
            </tr>
        </table>
        <table>
            <tr>
                <td><input type=submit name="action" value="Guardar"></td>
                <td><input type=submit name="action" value="Guardar y Continuar"></td>
                <td><button type=submit name="action" value="Salir" onclick="return confirm('Los datos no ser&aacute;n almacenados');">Cancelar</button></td>
            </tr>
        </table>
    </form>
{% endblock %}

app/templates/roles/modificar_roles.html
{% extends "base.html" %}
{% block title %}Modificar Roles{% endblock %}
{% block body %}
    <h2>Modificar Roles</h2>
    {% if error %}<div class=error><strong>Error: </strong>{{ error }}</div>{% endif %}
    <form action="" method=post>
        <table>
            <tr>
                <td>(*) Nombre:</td>
                <td><input type=text name=nombre size=15 maxlength=15 value="{{ nombre }}"></td>
            </tr>
            <tr>
                <td>(*) Descripci&oacute;n:</td>
                <td><input type=text name=descripcion size=30 maxlength=30 value="{{ descripcion }}"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>(*) Datos requeridos</td>
            </tr>
        </table>
        <table>
            <tr>
                <td><input type=submit name="action" value="Guardar"></td>
                <td><button type=submit name="action" value="Salir" onclick="return confirm('Los datos no ser&aacute;n almacenados');">Cancelar</button></td>
            </tr>
        </table>
</form>
{% endblock %}