app/mod_auth/views.py
# Import flask dependencies
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for

from app import login_required
from app.mod_auth import controllers

# Define the blueprint
mod_auth = Blueprint('auth', __name__, url_prefix='/auth')

# Set the route and accepted methods
@mod_auth.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        validacion = controllers.verificar_login(username, password)
        if validacion:
            session['id_usuario'] = username
            return redirect(url_for('auth.menu_principal'))
        else:
            error = 'Login Incorrecto'
    return render_template('auth/login.html', error=error, password='')

@mod_auth.route('/logout')
def logout():
    session.pop('id_usuario', None)
    session.clear()
    return redirect(url_for('auth.login'))

@mod_auth.route('/menu_principal')
@login_required
def menu_principal():
    error = None
    id_usuario = session['id_usuario']
    session['busqueda'] = False
    return render_template('auth/menu_principal.html', error=error, \
    id_usuario=id_usuario)

app/templates/base.html
<!doctype html>
<title>{% block title %}Bienvenido{% endblock %} | Consola de Administraci&oacute;n</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<div class=page>
  <h1>Consola de Administraci&oacute;n</h1>
  <div class=navigation>
  {% if id_usuario %}
    <a href="{{ url_for('auth.logout') }}">Salir [{{ id_usuario }}]</a>
  {% else %}
    <a href="{{ url_for('auth.login') }}">Ingresar</a>
  {% endif %}
  </div>
  {% with flashes = get_flashed_messages() %}
    {% if flashes %}
      <ul class=flashes>
      {% for message in flashes %}
        <li>{{ message }}
      {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
  <div class=body>
  {% block body %}{% endblock %}
  </div>
  <div class=footer>
    Una Aplicaci&oacute;n Flask
  </div>
</div>

app/templates/error_permisos.html
{% extends "base.html" %}
{% block title %}No Autorizado{% endblock %}
{% block body %}
  {% if error %}<div class=error><strong>Error:</strong> {{ error }}</div>{% endif %}
    <h3 align="center">No cuenta con los permisos requeridos para realizar la acci&oacute;n</h3>
    <br/>
    <div align="center"><input type=submit name="action" value=Regresar onclick="history.back();"></div>
{% endblock %}